### PR TITLE
fix: update Credential status when Region is not ready

### LINKED ISSUE #2056: [bug][nit] Regional credential still valid after corresponding Region object removal
**Describe the bug**
Credential, created for region remains valid and available for usage after Region object is removed.

**To Reproduce**
1. Deploy any cluster 
2. Create Region referencing that cluster
3. Create any credential set (for aws  - secret, awssi in regional and credential in mgmt)
4. Remove Region
5. Check credential

**Expected behavior**
Credential should not valid anymore

**Additional context**
Credential no more valid only if the corresponding ex-regional cluster is removed.

### PR DESCRIPTION
**Pull request by eromanova**
**What this PR does / why we need it**:
Currently, when the Region is removed, the Credential object remains valid. This PR fixes it and sets the up-to-date status to the regional Credential object.

**Which issue(s) this PR fixes** _(optional, `Fixes #123`)_:
Fixes #2056

### CODE REVIEW

File: internal/controller/credential_controller.go [hunk 1]
```diff
@@ -72,16 +76,38 @@ func (r *CredentialReconciler) Reconcile(ctx context.Context, req ctrl.Request)
...
+		}
+		if failedMsg != "" {
+			apimeta.SetStatusCondition(cred.GetConditions(), metav1.Condition{
+				Type:               kcmv1.CredentialReadyCondition,
+				Status:             metav1.ConditionFalse,
+				Reason:             kcmv1.FailedReason,
+				ObservedGeneration: cred.Generation,
+				Message:            failedMsg,
+			})
+			return ctrl.Result{}, errors.New(failedMsg)
```
Comment (zerospiel) [inline internal/controller/credential_controller.go]: do we actually have to requeue here with an error? Maybe it makes sense to return with an error only if there was a problem getting the `regions` object, otherwise just update the status and "done" (empty result with no error). wdyt?

File: api/v1beta1/indexers.go [hunk 2]
```diff
@@ -387,3 +390,21 @@ func ExtractServiceSetProvider(o client.Object) []string {
...
+
+// CredentialRegionIndexKey indexer field name to extract region name from [Credential] object.
+const CredentialRegionIndexKey = "spec.region"
+
+func setupCredentialRegionIndexer(ctx context.Context, mgr ctrl.Manager) error {
+	return mgr.GetFieldIndexer().IndexField(ctx, &Credential{}, CredentialRegionIndexKey, ExtractCredentialRegion)
+}
+
+// ExtractCredentialRegion returns the region name from [Credential] object.
+func ExtractCredentialRegion(o client.Object) []string {
```
Comment (zerospiel) [inline api/v1beta1/indexers.go]: nit: i do not see the reason for the function to be public (there are no tests yet for this function to be called outside the package)

File: internal/controller/credential_controller.go (hunk 1 above)
Comment (eromanova) [reply internal/controller/credential_controller.go]: You're right. It doesn’t make much sense to keep requeuing until the region exists.

File: internal/controller/credential_controller.go [hunk 3]
```diff
@@ -72,16 +76,38 @@ func (r *CredentialReconciler) Reconcile(ctx context.Context, req ctrl.Request)
...
-		})
-		return ctrl.Result{}, err
+	rgnClient := r.MgmtClient
+	if cred.Spec.Region != "" {
+		var failedMsg string
+		rgn := &kcmv1.Region{}
+		if err = r.MgmtClient.Get(ctx, client.ObjectKey{Name: cred.Spec.Region}, rgn); err != nil {
+			failedMsg = fmt.Sprintf("Failed to get Region %s: %v", cred.Spec.Region, err)
+		}
+		if rgn != nil && !rgn.DeletionTimestamp.IsZero() {
```
Comment (zerospiel) [inline internal/controller/credential_controller.go]:
```suggestion
		if !rgn.DeletionTimestamp.IsZero() {
```

nit: `v := &<>{}` and `v := new(<>)` already allocate an object in a span in the memory area

Comment (eromanova) [reply internal/controller/credential_controller.go]: Correct. Thank you.

**Review by zerospiel — APPROVED** [review]
