### PR TITLE
Do not drop unused kcm templates HelmReleases

### LINKED ISSUE #1279: [bug] KCM controller continuously creates and removes the templates helmrelease for inactive release
**Describe the bug**
KCM controller continuously creates and removes the `HelmRelease` with kcm templates for inactive release:
```
2025-03-25T17:14:03Z	INFO	Found component to remove	{"controller": "management", "controllerGroup": "k0rdent.mirantis.com", "controllerKind": "Management", "Management": {"name":"kcm"}, "namespace": "", "name": "kcm", "reconcileID": "5a699fa4-02ff-4f72-86e3-c451453fea40", "component_name": "kcm-0-2-0-rc1-tpl"}
2025-03-25T17:14:03Z	INFO	Removed HelmRelease	{"controller": "management", "controllerGroup": "k0rdent.mirantis.com", "controllerKind": "Management", "Management": {"name":"kcm"}, "namespace": "", "name": "kcm", "reconcileID": "5a699fa4-02ff-4f72-86e3-c451453fea40", "reference": "kcm-system/kcm-0-2-0-rc1-tpl"}
2025-03-25T17:14:05Z	INFO	Successfully created kcm-system/kcm-0-2-0-rc1-tpl HelmRelease	{"controller": "release", "controllerGroup": "k0rdent.mirantis.com", "controllerKind": "Release", "Release": {"name":"kcm-0-2-0-rc1"}, "namespace": "", "name": "kcm-0-2-0-rc1", "reconcileID": "5bfee4b0-6f8e-4699-986c-27aa2eee6717"}
2025-03-25T17:14:05Z	INFO	HelmRelease is not ready yet, retrying	{"controller": "release", "controllerGroup": "k0rdent.mirantis.com", "controllerKind": "Release", "Release": {"name":"kcm-0-2-0-rc1"}, "namespace": "", "name": "kcm-0-2-0-rc1", "reconcileID": "5bfee4b0-6f8e-4699-986c-27aa2eee6717", "namespace": "kcm-system", "name": "kcm-0-2-0-rc1-tpl"}
2025-03-25T17:14:13Z	INFO	Found component to remove	{"controller": "management", "controllerGroup": "k0rdent.mirantis.com", "controllerKind": "Management", "Management": {"name":"kcm"}, "namespace": "", "name": "kcm", "reconcileID": "4b5cb4a2-6b28-4e20-864e-6c5a04024de7", "component_name": "kcm-0-2-0-rc1-tpl"}
2025-03-25T17:14:13Z	INFO	Removed HelmRelease	{"controller": "management", "controllerGroup": "k0rdent.mirantis.com", "controllerKind": "Management", "Management": {"name":"kcm"}, "namespace": "", "name": "kcm", "reconcileID": "4b5cb4a2-6b28-4e20-864e-6c5a04024de7", "reference": "kcm-system/kcm-0-2-0-rc1-tpl"}
2025-03-25T17:14:15Z	INFO	Successfully created kcm-system/kcm-0-2-0-rc1-tpl HelmRelease	{"controller": "release", "controllerGroup": "k0rdent.mirantis.com", "controllerKind": "Release", "Release": {"name":"kcm-0-2-0-rc1"}, "namespace": "", "name": "kcm-0-2-0-rc1", "reconcileID": "51c7d792-3c54-4e5e-9aad-6e1a7cfce821"}
2025-03-25T17:14:15Z	INFO	HelmRelease is not ready yet, retrying	{"controller": "release", "controllerGroup": "k0rdent.mirantis.com", "controllerKind": "Release", "Release": {"name":"kcm-0-2-0-rc1"}, "namespace": "", "name": "kcm-0-2-0-rc1", "reconcileID": "51c7d792-3c54-4e5e-9aad-6e1a7cfce821", "namespace": "kcm-system", "name": "kcm-0-2-0-rc1-tpl"}
```

**To Reproduce**
1. Deploy K0rdent 0.1.0. Wait for it to be ready.
2. Create new Release `0.2.0-rc1`. Wait for new templates to be created
3. New templates were created and are not removed since templates have helm `keep` annotation but `HelmRelease` keeps creating/removing

**Expected behavior**
New templates are installed and the HelmRelease persists.

### PR DESCRIPTION
**Pull request by eromanova**
Closes #1279

### CODE REVIEW

File: internal/controller/management_controller.go [hunk 1]
```diff
@@ -306,9 +306,17 @@ func (r *ManagementReconciler) cleanupRemovedComponents(ctx context.Context, man
 
 		componentName := hr.Name // providers(components) names map 1-1 to the helmreleases names
 
+		releasesList := &metav1.PartialObjectMetadataList{}
+		releasesList.SetGroupVersionKind(kcm.GroupVersion.WithKind(kcm.ReleaseKind))
+		if err := r.Client.List(ctx, releasesList); err != nil {
+			return fmt.Errorf("failed to list releases: %w", err)
+		}
```
Comment (zerospiel) [inline internal/controller/management_controller.go:313]: i believe we could call the `list` just once before the loop

**Review by zerospiel — CHANGES_REQUESTED** [review]

File: internal/controller/management_controller.go (hunk 1 above)
Comment (eromanova) [reply internal/controller/management_controller.go:313]: Oh, right. Thanks.

Comment (zerospiel) [reply internal/controller/management_controller.go:313]: and just in case, i'd call the `list` only if `len(managedHelmReleases.Items) > 0`

**Review by zerospiel — APPROVED** [review]

**Comment by zerospiel** [comment]
To be cherry-picked, right? As well as #1282 and #1284

**Comment by eromanova** [comment]
> To be cherry-picked, right? As well as https://github.com/k0rdent/kcm/pull/1282 and https://github.com/k0rdent/kcm/pull/1284
Yes, I'll prepare the PRs in the `main` branch soon.
