### PR TITLE
fix: validate only diff during object updates

### LINKED ISSUE #2033: [bug] Admission should validate the diff, not the resource itself
The admission webhook should only validate the differences between the current and the applied configuration. For example, if a ProviderTemplate has already been added to the Management object, it should not block modifications to the Management object.

### PR DESCRIPTION
**Pull request by eromanova**
**What this PR does / why we need it**:
This PR fixes the admission webhook behaviour on Update requests so that it validates only diffs rather than the entire object. It's needed to allow valid object updates even if some previously configured field (ex., the ProviderTemplate configuration in the Management object) has since become invalid.

Contains:
1. Validate the Credential during ClusterDeployment update only if `spec.credential` was updated.
2. Validate Services (service templates and dependencies) during ClusterDeployment update only if `spec.serviceSpec.services` was updated.
3. Validate ProviderTemplates (validity, contracts compatibility) during Management/Region update only if the ProviderTemplate was updated.
4. Refactor Management and Region validation functions.
5. Update and adjust unit tests accordingly.

**Which issue(s) this PR fixes** _(optional, `Fixes #123`)_:
Fixes #2033

### CODE REVIEW

File: internal/util/validation/mgmt.go [hunk 1]
```diff
@@ -55,24 +53,77 @@ func GetIncompatibleContracts(ctx context.Context, cl client.Client, release *kc
...
+
+	for _, tplName := range templateNames {
 		pTpl := new(kcmv1.ProviderTemplate)
 		if err := cl.Get(ctx, client.ObjectKey{Name: tplName}, pTpl); err != nil {
 			return "", fmt.Errorf("failed to get ProviderTemplate %s: %w", tplName, err)
 		}
 
 		if len(pTpl.Status.CAPIContracts) == 0 {
-			continue
+			return "", nil
```
Comment (zerospiel) [inline internal/util/validation/mgmt.go]: why have we changed the logic here? shouldn't we check all of the provider templates?

some unit tests to check the logic would be appreciated because the logic is not a light breeze and changes to it might break in an unexpected way

Comment (eromanova) [reply internal/util/validation/mgmt.go]: That's definitely a leftover that was added by mistake during refactoring and should be fixed. Thanks, Michael.

**Review by zerospiel — APPROVED** [review]
