### PR TITLE
Adjust `cld` and `mcs` statuses

### LINKED ISSUE #813: [bug] Incorrect `ManagedCluster` status
**Describe the bug**
The cluster itself is healthy, but the services included in cluster spec and which were expected to be deployed in the cluster are not.

Deployed cluster with a set of services in spec:

```yaml
apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: abortnikov-hmc-managed-01
  namespace: hmc-system
spec:
  template: aws-standalone-cp-0-0-4
  credential: aws-cluster-identity-cred
  services:
    - template: cert-manager-1-16-2
      name: managed-cert-manager
      namespace: cert-manager
    - template: external-secrets-0-11-0
      name: managed-external-secrets
      namespace: external-secrets
```

After a while it became "Ready":

```shell
> k get -nhmc-system managedclusters.hmc.mirantis.com                                                                                                                                                                         ⎈ kind-hmc-dev  16:00:09
NAME                        READY   STATUS
abortnikov-hmc-managed-01   True    ManagedCluster is ready
```

However, this is not true: only one of two services was deployed and due to missing configuration it never entered "ready" state (cert-manager pods continuously restarting due to missing CRDs).
This is reflected in the `.status.services` of the managed cluster, but the conditions are Ok:

```shell
> k get -nhmc-system managedclusters.hmc.mirantis.com abortnikov-hmc-managed-01 -oyaml
apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: abortnikov-hmc-managed-01
  namespace: hmc-system
...
status:
  conditions:
  ...
  - lastTransitionTime: "2024-12-18T19:38:08Z"
    message: ""
    reason: Succeeded
    status: "True"
    type: SveltosProfileReady
  - lastTransitionTime: "2024-12-18T19:34:54Z"
    message: ""
    reason: Succeeded
    status: "True"
    type: FetchServicesStatusSuccess
  ...
  services:
  - clusterName: abortnikov-hmc-managed-01
    clusterNamespace: hmc-system
    conditions:
    - lastTransitionTime: "2024-12-19T14:00:01Z"
      message: "failed post-install: 1 error occurred:\n\t* job managed-cert-manager-startupapicheck
        failed: BackoffLimitExceeded\n\n"
      reason: Provisioning
      status: "False"
      type: Helm
```

**To Reproduce**
1. Deploy `ManagedCluster` with cert-manager service included. Due to CRDs' installation disabled by default in cert-manager Helm chart the service deployment will fail
2. Wait until cluster becomes "Ready"

**Expected behavior**
It is expected that the `ManagedCluster` state should consider also state of services included to the spec.

### LINKED ISSUE #1027: Extend `kubectl get clusterdeployment` output
Please extend the command output to improve user experience:

~~~
kubectl get clusterdeployment
~~~

# Current
~~~
NAME       READY   STATUS
cluster1   True    ClusterDeployment is ready*
cluster2   True    ClusterDeployment is ready
~~~
* `ClusterDeployment is ready` should be just `Ready`
* Column `SERVICES` could show deployed/not deployed services counts.

# Suggested
~~~
NAME       STATUS      SERVICES      AGE
cluster1   Processing  3/5           2d12h
cluster2   Ready       2/2           2d12h
~~~

### LINKED ISSUE #1028: Extend `kubectl get multiclusterservice` output
Please extend the command output to improve user experience:

~~~
kubectl get multiclusterservice
~~~

# Current
~~~
NAME                AGE
mcs-nginx-ingress   2d12h
~~~

# Suggested
~~~
NAME               STATUS       SERVICES     CLUSTERS   AGE
mcs-nginx-ingress  Creating     3/5          0/2        2d12h
~~~
* Column `STATUS` - `Running / Pending / Failed / Succeeded / Unknown`
* Column `SERVICES` - Deployed/Required services count.
* Column `CLUSTERS` - Updated/NotUpdated clusters count.

### PR DESCRIPTION
**Pull request by zerospiel**
* add number of ready services condition to `cld`/`mcs` statuses
* add number of ready clusters condition to `mcs` status
* print the new conditions in custom columns
* adjust `cld` print columns
* calculate `cld`/`mcs` readiness based on services readiness
* calculate `mcs` readiness based on selected clusters readiness
* add short name to `mcs` resource

Closes #1028 
Closes #1027
Closes #813

### CODE REVIEW

File: internal/controller/multiclusterservice_controller.go [hunk 1]
```diff
@@ -192,40 +198,133 @@ func (r *MultiClusterServiceReconciler) updateStatus(ctx context.Context, mcs *k
...
+	ready := 0
+	for _, svcstatus := range serviceStatuses {
+		svcready := true
+		if slices.ContainsFunc(svcstatus.Conditions, func(e metav1.Condition) bool { return e.Status != metav1.ConditionTrue }) {
+			svcready = false
+		}
+
+		if svcready {
+			ready++
+		}
```
Comment (eromanova) [inline internal/controller/multiclusterservice_controller.go:263]: Can it be simplified a bit?
```suggestion
		if !slices.ContainsFunc(svcstatus.Conditions, func(e metav1.Condition) bool { return e.Status != metav1.ConditionTrue }) {
			ready++
		}
```

**Review by eromanova — COMMENTED** [review]
LGTM

File: internal/controller/multiclusterservice_controller.go (hunk 1 above)
Comment (zerospiel) [reply internal/controller/multiclusterservice_controller.go]: it can. thanks!
